(function(){
// Polyfills
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector||function(s){var m=(this.document||this.ownerDocument).querySelectorAll(s),i=m.length;while(--i>=0&&m.item(i)!==this){}return i>-1;};}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;if(!document.documentElement.contains(el))return null;do{if(el.matches(s))return el;el=el.parentElement||el.parentNode;}while(el!==null&&el.nodeType===1);return null;};}

// Store (classic pre-notes)
var store;try{store=JSON.parse(localStorage.getItem('kazuma_pos_store')||'{}');}catch(e){store={};}
store.products=store.products||[];store.promos=store.promos||[];store.sales=store.sales||[];store.settings=store.settings||{theme:'#1662ff',currencySymbol:'$',lowStockThreshold:5};
function saveStore(){try{localStorage.setItem('kazuma_pos_store',JSON.stringify(store));}catch(e){}}
function uid(){return'p'+Math.random().toString(36).slice(2,10);}function money(n){var sym=(store.settings&&store.settings.currencySymbol)||'$';return sym+Number(n||0).toFixed(2);}
function byId(id){return document.getElementById(id);}function qs(sel){return document.querySelector(sel);}function qsa(sel){return Array.from(document.querySelectorAll(sel));}

// Routing
var SECTION_NAME={catalog:'產品目錄',cart:'購物車',manage:'產品管理',promo:'優惠設定',sales:'銷售紀錄',io:'匯入/匯出',settings:'設定'};
function highlightNav(){var target=(location.hash||'').slice(1)||'section-catalog';var sec=target.replace('section-','');qsa('#nav a').forEach(a=>{a.classList.remove('active');a.removeAttribute('aria-current');});var link=qs('#nav a[data-section=\"'+sec+'\"]');if(link){link.classList.add('active');link.setAttribute('aria-current','page');}var ind=byId('pageIndicator');if(ind)ind.textContent='目前頁面：'+(SECTION_NAME[sec]||sec);if(sec==='catalog')renderCatalog();if(sec==='cart')renderCart();if(sec==='manage')renderProductTable();if(sec==='promo')renderPromos();if(sec==='sales')renderSales();if(sec==='settings')renderSettings();}
window.addEventListener('hashchange',highlightNav);document.addEventListener('DOMContentLoaded',function(){if(!location.hash)location.hash='#section-catalog';highlightNav();},false);

// Theme
function markActiveTheme(color){qsa('.theme-swatch').forEach(s=>{s.classList.remove('active');if(s.getAttribute('data-color')===color)s.classList.add('active');});}
function applyTheme(color){document.documentElement.style.setProperty('--pri',color);store.settings.theme=color;saveStore();markActiveTheme(color);}
function renderTheme(){var list=byId('themeList');if(!list)return;list.innerHTML='';['#1662ff','#0ea5e9','#22c55e','#f59e0b','#ef4444','#a855f7','#111827','#10b981','#3b82f6','#e11d48','#f97316'].forEach(c=>{var d=document.createElement('div');d.className='theme-swatch';d.style.background=c;d.title=c;d.setAttribute('data-color',c);d.addEventListener('click',()=>applyTheme(c));list.appendChild(d);});applyTheme(store.settings.theme||'#1662ff');markActiveTheme(store.settings.theme||'#1662ff');}
function renderSettings(){var inp=byId('currencySymbolInput');if(inp){inp.value=(store.settings&&store.settings.currencySymbol)||'$';inp.addEventListener('change',function(){store.settings.currencySymbol=this.value||'$';saveStore();renderCart();renderProductTable();renderCatalog();renderSales();});}
var low=byId('lowStockInput');if(low){low.value=(store.settings&&(store.settings.lowStockThreshold??5));low.addEventListener('change',function(){store.settings.lowStockThreshold=Math.max(0,Number(this.value||5));saveStore();});}renderTheme();}

// Manage
function resetForm(){['pName','pCategory','pPrice','pCost','pSpecial','pStock','pTags','pImageUrl','pImageFile'].forEach(id=>{var el=byId(id);if(!el)return;if(el.type==='file')el.value='';else el.value='';});window.editingId=null;}
var _saveLock=false;
function saveProductAction(){if(_saveLock)return;_saveLock=true;setTimeout(()=>{_saveLock=false;},500);var name=byId('pName').value.trim();if(!name){alert('請輸入商品名稱');return;}var p={id:window.editingId||uid(),name,category:byId('pCategory').value.trim(),price:Number(byId('pPrice').value||0),cost:Number(byId('pCost').value||0),specialPrice:(byId('pSpecial').value===''?null:Number(byId('pSpecial').value)),stock:Number(byId('pStock').value||0),tags:byId('pTags').value.split(',').map(s=>s.trim()).filter(Boolean),image:null};var file=byId('pImageFile').files[0];var url=byId('pImageUrl').value.trim();function done(){saveProduct(p);resetForm();alert('已儲存商品');}if(file){var fr=new FileReader();fr.onload=function(){p.image=fr.result;done();};fr.onerror=function(){alert('圖片讀取失敗');done();};fr.readAsDataURL(file);}else if(url){p.image=url;done();}else{if(window.editingId){var old=store.products.find(x=>x.id===window.editingId);p.image=old&&old.image||null;}done();}}
function saveProduct(p){var idx=store.products.findIndex(x=>x.id===p.id);if(idx>=0)store.products[idx]=p;else store.products.push(p);saveStore();renderProductTable();renderCatalog();}
function _bindManageButtons(){var mf=byId('manageForm');if(mf&&!mf._bound){mf.addEventListener('submit',function(e){e.preventDefault();saveProductAction();},false);mf.addEventListener('reset',function(e){e.preventDefault();resetForm();},false);mf._bound=true;}var saveBtn=byId('saveProductBtn');var resetBtn=byId('resetFormBtn');function bind(btn,fn){if(!btn||btn._bound)return;var handler=function(e){e.preventDefault();e.stopPropagation();try{fn();}catch(err){}};['click','touchend','pointerup'].forEach(ev=>{btn.addEventListener(ev,handler,{passive:false});});btn._bound=true;}bind(saveBtn,saveProductAction);bind(resetBtn,resetForm);var sec=byId('section-manage');if(sec&&!sec._delegated){sec.addEventListener('click',function(e){if(e.target&&e.target.id==='saveProductBtn'){e.preventDefault();saveProductAction();}if(e.target&&e.target.id==='resetFormBtn'){e.preventDefault();resetForm();}},true);sec._delegated=true;}}
document.addEventListener('DOMContentLoaded',_bindManageButtons,false);window.addEventListener('hashchange',function(){if((location.hash||'').indexOf('#section-manage')===0)_bindManageButtons();});
function renderProductTable(){var tb=byId('productTable').querySelector('tbody');tb.innerHTML='';store.products.forEach(p=>{var tr=document.createElement('tr');tr.className='product-row';var img=p.image?'<img src=\"'+p.image+'\">':'';var price=p.specialPrice!=null?money(p.price)+' / <b>'+money(p.specialPrice)+'</b>':money(p.price);var tags=(p.tags||[]).join(', ');tr.innerHTML='<td>'+img+'</td><td>'+p.name+'</td><td>'+(p.category||'')+'</td><td>'+price+'</td><td>'+money(p.cost||0)+'</td><td>'+(p.stock||0)+'</td><td>'+tags+'</td><td><button data-edit=\"'+p.id+'\">編輯</button> <button data-del=\"'+p.id+'\">刪除</button></td>';tb.appendChild(tr);});}
document.addEventListener('click',function(e){var edit=e.target.closest('[data-edit]');if(edit){var id=edit.getAttribute('data-edit');var p=store.products.find(x=>x.id===id);if(!p)return;window.editingId=id;byId('pName').value=p.name||'';byId('pCategory').value=p.category||'';byId('pPrice').value=p.price||0;byId('pCost').value=p.cost||0;byId('pSpecial').value=p.specialPrice==null?'':p.specialPrice;byId('pStock').value=p.stock||0;byId('pTags').value=(p.tags||[]).join(', ');byId('pImageUrl').value=p.image&&p.image.startsWith('http')?p.image:'';location.hash='#section-manage';}
var del=e.target.closest('[data-del]');if(del){var id=del.getAttribute('data-del');if(confirm('確定刪除商品？')){store.products=store.products.filter(x=>x.id!==id);saveStore();renderProductTable();renderCatalog();}}},true);

// Catalog & search
function buildAllTags(){var set=new Set();store.products.forEach(p=>(p.tags||[]).forEach(t=>set.add(t)));return Array.from(set).sort();}
function renderTagChips(){var wrap=byId('tagChips');wrap.innerHTML='';buildAllTags().forEach(t=>{var s=document.createElement('span');s.className='tag';s.textContent=t;s.addEventListener('click',()=>{s.classList.toggle('active');renderCatalog();});wrap.appendChild(s);});}
function matchesSearch(p,q,activeTags){q=(q||'').trim().toLowerCase();if(q&&!((p.name+' '+p.category+' '+(p.tags||[]).join(' ')).toLowerCase().includes(q)))return false;if(activeTags.length&&!activeTags.every(t=>(p.tags||[]).includes(t)))return false;return true;}
function renderCatalog(){renderTagChips();var q=byId('searchInput').value||'';var activeTags=Array.from(byId('tagChips').querySelectorAll('.tag.active')).map(x=>x.textContent);var grid=byId('catalogGrid');grid.innerHTML='';store.products.filter(p=>matchesSearch(p,q,activeTags)).forEach(p=>{var card=document.createElement('div');card.className='card';var img=p.image?'<img src=\"'+p.image+'\" alt=\"\">':'';var price=p.specialPrice!=null?'<div>售價：<s>'+money(p.price)+'</s> <b>'+money(p.specialPrice)+'</b></div>':'<div>售價：'+money(p.price)+'</div>';card.innerHTML=img+'<div><b>'+p.name+'</b><div class=\"muted\">'+(p.category||'')+'</div>'+price+'</div><div class=\"row\"><button data-add=\"'+p.id+'\" class=\"primary\" type=\"button\">加入</button></div>';grid.appendChild(card);});}
byId('searchInput').addEventListener('input',()=>renderCatalog());

// Cart / Mini
var cart=JSON.parse(sessionStorage.getItem('kazuma_pos_cart')||'[]');function saveCart(){sessionStorage.setItem('kazuma_pos_cart',JSON.stringify(cart));}
function findPromo(category){return store.promos.find(x=>(x.category||'').toLowerCase()===(category||'').toLowerCase());}
function computeLine(p,qty){var unit=p.specialPrice!=null?Number(p.specialPrice):Number(p.price);var promo=findPromo(p.category);var free=0;if(promo&&promo.buy>0&&promo.get>0){free=Math.floor(qty/(promo.buy+promo.get))*promo.get;}var payQty=Math.max(0,qty-free);var subtotal=unit*payQty;return{unit,free,payQty,subtotal};}
var lastAddTs=0;
document.addEventListener('click',function(e){var add=e.target.closest('[data-add]');if(add){if(e.timeStamp&&(e.timeStamp-lastAddTs)<350){return;}lastAddTs=e.timeStamp||Date.now();addToCart(add.getAttribute('data-add'),1);e.preventDefault();}
var inc=e.target.closest('[data-inc]');if(inc){addToCart(inc.getAttribute('data-inc'),1);e.preventDefault();}
var dec=e.target.closest('[data-dec]');if(dec){addToCart(dec.getAttribute('data-dec'),-1);e.preventDefault();}
var rem=e.target.closest('[data-remove]');if(rem){cart=cart.filter(x=>x.id!==rem.getAttribute('data-remove'));saveCart();renderCart();renderMiniCart();e.preventDefault();}
if(e.target.closest('#clearCartBtn')){if(confirm('清空購物車？')){cart=[];saveCart();renderCart();renderMiniCart();}}
if(e.target.closest('#miniToCart')){location.hash='#section-cart';}
if(e.target.closest('#miniCartClose')){byId('miniCart').hidden=true;updateFab();}
if(e.target.closest('#cartFab')){byId('miniCart').hidden=false;updateFab();}
if(e.target.closest('#miniCheckout')||e.target.closest('#checkoutBtn')){checkout();}},true);
function addToCart(id,delta){delta=delta||1;var p=store.products.find(x=>x.id===id);if(!p)return;var line=cart.find(x=>x.id===id);if(!line){line={id:id,qty:0};cart.push(line);}var targetQty=(line.qty||0)+delta;var available=Number(p.stock||0);if(targetQty>available){alert('庫存不足：'+p.name+'　剩餘 '+available);targetQty=available;}line.qty=Math.max(0,targetQty);if(line.qty===0)cart=cart.filter(x=>x.id!==id);saveCart();renderCart();renderMiniCart();byId('miniCart').hidden=false;var miniSel=byId('miniPaymentMethod');if(miniSel){var mainVal=(byId('paymentMethod')&&byId('paymentMethod').value)||'Cash';if(!miniSel.value)miniSel.value=mainVal;}updateFab();}
function renderCart(){var tb=byId('cartTable').querySelector('tbody');tb.innerHTML='';var total=0;cart.forEach(line=>{var p=store.products.find(x=>x.id===line.id);if(!p)return;var comp=computeLine(p,line.qty);total+=comp.subtotal;var tr=document.createElement('tr');tr.innerHTML='<td>'+p.name+'</td><td>'+money(comp.unit)+'</td><td><button data-dec=\"'+p.id+'\">-</button> '+line.qty+' <button data-inc=\"'+p.id+'\">+</button></td><td>'+comp.free+'</td><td>'+money(comp.subtotal)+'</td><td><button data-remove=\"'+p.id+'\">移除</button></td>';tb.appendChild(tr);});byId('cartTotal').textContent='總計：'+money(total);try{renderOrderNoteUI();}catch(e){}}
function renderMiniCart(){var body=byId('miniCartBody');body.innerHTML='';var total=0;cart.forEach(line=>{var p=store.products.find(x=>x.id===line.id);if(!p)return;var comp=computeLine(p,line.qty);total+=comp.subtotal;var row=document.createElement('div');row.className='mini-line';row.innerHTML='<div><div><b>'+p.name+'</b> <span class=\"muted\">'+money(comp.unit)+' / 贈 '+comp.free+'</span></div></div><div class=\"mini-qty\"><button data-dec=\"'+p.id+'\">-</button><span>'+line.qty+'</span><button data-inc=\"'+p.id+'\">+</button><div style=\"width:70px;text-align:right\">'+money(comp.subtotal)+'</div></div>';body.appendChild(row);});byId('miniCartTotal').textContent='總計：'+money(total);updateFab();try{renderOrderNoteUI();}catch(e){}}
function updateFab(){var fab=byId('cartFab');var count=byId('cartFabCount');var totalQty=cart.reduce((a,b)=>a+(b.qty||0),0);if(cart.length>0){count.textContent=String(totalQty);fab.hidden=!byId('miniCart').hidden;}else{fab.hidden=true;byId('miniCart').hidden=true;}}

// Checkout & sales
function checkout(){if(!cart.length){alert('購物車是空的');return;}var shortages=[];cart.forEach(line=>{var p=store.products.find(x=>x.id===line.id);if(p&&line.qty>Number(p.stock||0))shortages.push(p.name+'（剩 '+p.stock+'）');});if(shortages.length){alert('以下商品庫存不足：\n'+shortages.join('\n'));return;}var payElMini=byId('miniPaymentMethod');var pay=(payElMini&&!byId('miniCart').hidden)?payElMini.value:byId('paymentMethod').value;var items=cart.map(line=>{var p=store.products.find(x=>x.id===line.id);var comp=computeLine(p,line.qty);return{id:p.id,name:p.name,category:p.category||'',unit:comp.unit,qty:line.qty,free:comp.free,subtotal:comp.subtotal,cost:p.cost||0};});items.forEach(it=>{var prod=store.products.find(x=>x.id===it.id);prod.stock=Math.max(0,(prod.stock||0)-it.qty);});var total=items.reduce((a,b)=>a+b.subtotal,0);var sale={id:'s'+Math.random().toString(36).slice(2,10),time:new Date().toISOString(),items,total,payment:pay,status:'完成',refund:false};if(orderNoteDraft&&orderNoteDraft.trim())sale.notes=orderNoteDraft.trim();store.sales.unshift(sale);store.settings.lastPayment=pay;saveStore();var threshold=(store.settings&&(store.settings.lowStockThreshold??5));var lows=store.products.filter(p=>Number(p.stock||0)<=Number(threshold||5)).map(p=>p.name+'（剩 '+p.stock+'）');cart=[];saveCart();renderCart();renderMiniCart();setOrderNoteDraft('');var on=document.getElementById('orderNote');if(on)on.value='';var mi=document.getElementById('miniOrderNote');if(mi)mi.value='';if(lows.length){alert('低庫存提醒：\n'+lows.join('\n'));}else{alert('交易完成');}}
function renderSales(){var from=byId('filterFrom').value?new Date(byId('filterFrom').value+'T00:00:00'):null;var to=byId('filterTo').value?new Date(byId('filterTo').value+'T23:59:59'):null;var pay=byId('filterPay').value||'';var list=store.sales.filter(s=>{var t=new Date(s.time);if(from&&t<from)return false;if(to&&t>to)return false;if(pay&&s.payment!==pay)return false;return true;});var tb=byId('salesTable').querySelector('tbody');tb.innerHTML='';var sum=0;list.forEach(s=>{sum+=s.total;var tr=document.createElement('tr');tr.innerHTML='<td>'+s.time.slice(0,19).replace('T',' ')+'</td><td>'+s.items.length+'</td><td>'+money(s.total)+'</td><td>'+s.payment+'</td><td>'+s.status+'</td><td><button data-detail=\"'+s.id+'\">詳情</button> <button data-refund=\"'+s.id+'\">退款/作廢</button></td>';tb.appendChild(tr);});byId('salesSummary').textContent='筆數：'+list.length+'　總額：'+money(sum);}
document.addEventListener('click',function(e){var d=e.target.closest('[data-detail]');if(d){var id=d.getAttribute('data-detail');var s=store.sales.find(x=>x.id===id);if(!s)return;var html='<div>時間：'+s.time.slice(0,19).replace('T',' ')+'　付款：'+s.payment+'　狀態：'+s.status+'</div>'+(s.notes?'<div>備註：'+esc(s.notes)+'</div>':'')+'<hr>';html+='<table class=\"table\"><thead><tr><th>品名</th><th>單價</th><th>數量</th><th>贈送</th><th>小計</th></tr></thead><tbody>';s.items.forEach(it=>{html+='<tr><td>'+it.name+'</td><td>'+money(it.unit)+'</td><td>'+it.qty+'</td><td>'+it.free+'</td><td>'+money(it.subtotal)+'</td></tr>';});html+='</tbody></table><div class=\"total\">總計：'+money(s.total)+'</div>';openModal('交易詳情',html);}var r=e.target.closest('[data-refund]');if(r){var id=r.getAttribute('data-refund');var s=store.sales.find(x=>x.id===id);if(!s)return;if(!confirm('確定將此交易標記為退款/作廢？'))return;s.status='退款/作廢';s.refund=true;saveStore();renderSales();}},true);
byId('applyFilterBtn').addEventListener('click',renderSales);
byId('exportCsvBtn').addEventListener('click',function(){var rows=[['時間','品名','數量','贈送','單價','小計','付款','狀態']];store.sales.forEach(s=>{s.items.forEach(it=>{rows.push([s.time,it.name,it.qty,it.free,it.unit,it.subtotal,s.payment,s.status]);});});var csv=rows.map(r=>r.map(x=>'\"'+String(x).replace(/\"/g,'\"\"')+'\"').join(',')).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sales.csv';a.click();});

// Promo
function renderPromos(){var tb=byId('promoTable').querySelector('tbody');tb.innerHTML='';store.promos.forEach(pr=>{var tr=document.createElement('tr');tr.innerHTML='<td>'+pr.category+'</td><td>'+pr.buy+'</td><td>'+pr.get+'</td><td><button data-delpr=\"'+pr.category+'\">刪除</button></td>';tb.appendChild(tr);});}
document.addEventListener('click',function(e){var del=e.target.closest('[data-delpr]');if(del){var cat=del.getAttribute('data-delpr');store.promos=store.promos.filter(x=>x.category!==cat);saveStore();renderPromos();}},true);
byId('addPromoBtn').addEventListener('click',function(){var cat=byId('promoCategory').value.trim();var buy=Number(byId('promoBuy').value||0);var get=Number(byId('promoGet').value||0);if(!cat||buy<=0||get<=0){alert('請正確輸入分類與買送數量');return;}var ex=store.promos.find(x=>x.category.toLowerCase()===cat.toLowerCase());if(ex){ex.buy=buy;ex.get=get;}else{store.promos.push({category:cat,buy:buy,get:get});}saveStore();renderPromos();alert('已更新優惠');});

// IO
byId('exportJsonBtn').addEventListener('click',function(){var data=JSON.stringify(store,null,2);var blob=new Blob([data],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kazuma-pos-backup.json';a.click();});
byId('importJsonFile').addEventListener('change',function(e){var f=e.target.files[0];if(!f)return;var fr=new FileReader();fr.onload=function(){try{var obj=JSON.parse(fr.result);store=obj;saveStore();renderProductTable();renderCatalog();renderPromos();renderSales();renderTheme();alert('匯入完成');}catch(err){alert('JSON 格式錯誤');}};fr.readAsText(f);});

// Modal
function openModal(title,html){byId('modalTitle').textContent=title;byId('modalBody').innerHTML=html;byId('modalBackdrop').hidden=false;}
function closeModal(){byId('modalBackdrop').hidden=true;}
byId('modalClose').addEventListener('click',closeModal);byId('modalOk').addEventListener('click',closeModal);
document.addEventListener('click',function(e){var mb=byId('modalBackdrop');if(mb&&!mb.hidden){var modal=mb.querySelector('.modal');if(modal&&!modal.contains(e.target)&&!e.target.closest('[data-detail]')){closeModal();}}},true);

// Seed
(function(){if(!store.products.length){store.products.push({id:uid(),name:'冷萃咖啡',category:'飲品',price:35,cost:10,specialPrice:null,stock:50,tags:['咖啡','冷萃'],image:''});store.products.push({id:uid(),name:'拿鐵',category:'飲品',price:40,cost:12,specialPrice:35,stock:60,tags:['咖啡','奶'],image:''});store.products.push({id:uid(),name:'牛角包',category:'麵包',price:25,cost:8,specialPrice:null,stock:30,tags:['可頌'],image:''});saveStore();}})();

// ===== Order Notes (add-on for classic 2.9) =====
var orderNoteDraft=(function(){try{return sessionStorage.getItem('kazuma_pos_ordernote')||'';}catch(e){return'';}})();
function setOrderNoteDraft(v){orderNoteDraft=(v||'');try{sessionStorage.setItem('kazuma_pos_ordernote',orderNoteDraft);}catch(e){}}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function renderOrderNoteUI(){var cartSec=document.getElementById('section-cart');var afterEl=document.getElementById('cartTotal');if(cartSec&&afterEl){var existing=document.getElementById('orderNote');if(!existing){var wrap=document.createElement('div');wrap.style.marginTop='10px';var ta=document.createElement('textarea');ta.id='orderNote';ta.placeholder='訂單備註（可留空）';ta.rows=2;ta.style.width='100%';ta.style.borderRadius='10px';ta.style.border='1px solid var(--line)';ta.style.padding='8px 10px';wrap.appendChild(ta);afterEl.parentNode.insertBefore(wrap,afterEl.nextSibling);ta.addEventListener('input',function(){setOrderNoteDraft(this.value);var mini=document.getElementById('miniOrderNote');if(mini&&mini.value!==this.value)mini.value=this.value;});}var taNow=document.getElementById('orderNote');if(taNow&&taNow.value!==orderNoteDraft)taNow.value=orderNoteDraft;}var miniFoot=document.querySelector('.mini-cart-footer');if(miniFoot){var miniRowId='miniNoteRow';var miniRow=document.getElementById(miniRowId);if(!miniRow){miniRow=document.createElement('div');miniRow.className='row';miniRow.id=miniRowId;var input=document.createElement('input');input.type='text';input.id='miniOrderNote';input.placeholder='訂單備註（可留空）';input.style.flex='1';miniRow.appendChild(input);var firstFootRow=miniFoot.firstElementChild;if(firstFootRow)miniFoot.insertBefore(miniRow,firstFootRow);else miniFoot.appendChild(miniRow);input.addEventListener('input',function(){setOrderNoteDraft(this.value);var ta=document.getElementById('orderNote');if(ta&&ta.value!==this.value)ta.value=this.value;});}var miniInput=document.getElementById('miniOrderNote');if(miniInput&&miniInput.value!==orderNoteDraft)miniInput.value=orderNoteDraft;}}document.addEventListener('DOMContentLoaded',renderOrderNoteUI,false);

})();